### PR TITLE
fix: cannot find module with package exports and support previous non-function configurations

### PR DESCRIPTION
**Pull request by 1aron**
- #537 
- https://github.com/semantic-release/semantic-release/issues/3130

Since upgrading to v11 we have lost these features:

- Force the configuration type to be a function
- `conventional-changelog-*` packages configured via objects are no longer supported

This is the version that Semantic Releases v23 has a mandatory dependency on. The side effects of supporting ESM presets outweigh the benefits.

Reproduction: https://github.com/1aron/techor/actions/runs/7667827891/job/20898475834

### CODE REVIEW

**Comment by travi** [comment]
as highlighted in our [release notes for v11](https://github.com/semantic-release/commit-analyzer/releases/tag/v11.0.0) the format expected by the conventional-changelog presets has changed. as long as you update to the latest versions of the preset you are using, you should get back to working just fine. if you have a custom preset, you will need to update it to match the new expectations of the conventional-changelog project

**Comment by 1aron** [comment]
@travi For this package, compatibility with older versions only requires:
```ts
if (typeof loadedConfig === "function") {
     loadedConfig = await loadedConfig(presetConfig);
}
```
Is the incompatibility motivated by more than just the cases in the test?

In addition, changing `import-from` to `import-from-esm` in v11 seems to have caused many side effects and issues, which does need to be weighed.

**Comment by travi** [comment]
> compatibility with older versions only requires

a major goal of the signature expectation update by conventional-changelog and how the presets are handled is to remove the need for conditional logic like this. all of the official presets now use the modern signature. if you are using a preset that does not align to the new expectations from conventional-changelog, the proper path forward is to fix that. either fork that project or contribute there. we will not accept updates here to support legacy presets.

> Is the incompatibility motivated by more than just the cases in the test?

the change was made by the conventional-changelog project. we use those packages as dependencies of this project. aligning to their updated path simplifies our project, so we see it as a good thing

> In addition, changing `import-from` to `import-from-esm` in v11 seems to have caused many side effects and issues, which does need to be weighed.

unless i completely misunderstand the problem, this is not an issue with `import-from` vs `import-from-esm`, but entirely related to the documented breaking change related to the conventional-changelog changes and our alignment to those changes

**Comment by 1aron** [comment]
@travi I think conventional-changelog changed to use asynchronous function configuration maybe because I added asynchronous function to it. 😂 https://github.com/conventional-changelog/conventional-changelog/pull/1065

I'll open another issue for `import-from-esm`.
